# Site settings
title: Maria Burata
description: > # this means to ignore newlines until "baseurl:"
  Em dic Maria Burata. La formació en massatge Ayurveda m’ha donat
  el privilegi d’estar en contacte amb l’altre en un aprenentatge
  constant del tractaments energètics i físics. Actualment m’estic
  formant com a osteòpata
baseurl: "/mariaburata.com" # the subpath of your site, e.g. /blog/
url: "" #"http://yourdomain.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
permalink: /blog/:title
sass:
    style: :compressed
exclude: ['_prose.yml','.editorconfig','.gitignore']
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      lang: cat
      lang-name: "català"
      lang-order: 1
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      lang: cat
      lang-name: "català"
      lang-order: 2
      permalink: /blog/:title
  -
    scope:
      path: es
      type: "pages"
    values:
      layout: page
      lang: es
      lang-name: "castellano"
      lang-order: 2
  -
    scope:
      path: es
      type: "posts"
    values:
      layout: post
      lang: es
      lang-name: "castellano"
      lang-order: 2
      permalink: /es/blog/:title
