name: Maria Burata
description:
  cat: "Massatge Ayurveda i Osteopatia a Barcelona"
  es: "Masaje Ayurveda y Osteopatía en Barcelona"
email: hola@mariaburata.com
tel: 620 191 209
prices:
  unit:
    local:
      "60 min": "35 eur"
      "90 min": "40 eur"
    home:
      "60 min": "60 eur"
      "90 min": "65 eur"
  pack3:
    local:
      "180 min": "95 eur"
      "270 min": "110 eur"
    home:
      "180 min": "170 eur"
      "270 min": "185 eur"
