name: Maria Burata
description:
  cat: "Massatge Ayurveda i Osteopatia a Barcelona"
  es: "Masaje Ayurveda y Osteopatía en Barcelona"
email: hola@mariaburata.com
tel: 620 191 209
prices:
  unit:
    local:
      "75 min": "50 eur"
  vat:
    cat: IVA inclòs
    es: IVA incluido
